name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-react-vite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies for admin
        working-directory: ./admin
        run: npm install

      - name: Build React app
        working-directory: ./admin
        run: npm run build

      - name: Install dependencies for user
        working-directory: ./user
        run: npm install

      - name: Build React user
        working-directory: ./user
        run: npm run build

  test-nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies for server
        working-directory: ./server
        run: npm install

      - name: Run tests
        working-directory: ./server
        run: npm test
