name: CI/CD for server

on:
  push:
    branches: [main]

## Stage 1: Check code quality
  check-code-quality:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies for server
        working-directory: ./server
        run: bun install

      - name: Run ESLint for server
        working-directory: ./server
        run: |
          echo "Running ESLint in normal mode"
          bunx eslint .
          echo "Running ESLint in debug mode"
          bunx eslint . --debug
          echo "Running ESLint with auto-fix"
          bunx eslint . --fix

## Stage 2: Build and push docker
  push-to-registry:
    needs: check-code-quality
    name: build and push server docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: login to docker registry
        uese: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: build and push docker
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: nupniichan/wbdt-server:latest

## Stage 3: Pull docker
  pull-project:
    need: push-to-registry
    name: Pull server from registry
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: pull docker image from registry
        run: |
          docker pull nupniichan/wbdt-server:latest
  
## Stage 4: Deploy
  deploy:
    needs: pull-project
    runs-on: [self-hosted, Linux, X64]
    name: Deploy to runner
    steps:
      - name: Remove current running Docker container and run
        run: |
          docker rm -f nupniichan/wbdt-server || true
          docker run --name nupniichan/wbdt-server -dp 5000:5000 nupniichan/wbdt-server:latest